### ISSUE TITLE
Facing Problem

### ISSUE THREAD

**Issue by chnouman** [mike183/PHP-TinyPNG#1]
Notice: Trying to get property of non-object in C:\xampp\htdocs\tinypngProject\tinypng.php on line 50

Notice: Trying to get property of non-object in C:\xampp\htdocs\tinypngProject\tinypng.php on line 50

Notice: Trying to get property of non-object in C:\xampp\htdocs\tinypngProject\tinypng.php on line 51

Notice: Trying to get property of non-object in C:\xampp\htdocs\tinypngProject\tinypng.php on line 51

Notice: Trying to get property of non-object in C:\xampp\htdocs\tinypngProject\tinypng.php on line 52

Notice: Trying to get property of non-object in C:\xampp\htdocs\tinypngProject\tinypng.php on line 52
SSL certificate problem: unable to get local issuer certificateCompression failed

**Comment by chnouman** [comment]
I'm doing this 
<?php
	require_once("TinyPNG1.php");
	// Create a new instance of TinyPNG
$tinypng = new TinyPNG("my_token");
if ($tinypng==null) {
	echo "nill";
	# code...
}else{
	echo "not nil";
}
		// Compress a single image
  		//increase max execution time of this script to 150 min:
                ini_set('max_execution_time', 9000);
            //increase Allowed Memory Size of this script:
            ini_set('memory_limit','960M');
$singleImage = $tinypng -> compress("http://allhdwallpapers.com/sandbox/mediamanage/uploads//1119428508349446.jpg", "output.png");


print_r($singleImage);

?>

**Comment by chnouman** [comment]
please let me know where i'm doing wrong

**Comment by mike183** [comment]
Hi @chnouman, would you mind sharing all of the relevant code? I.e from instantiating the `TinyPNG` class through to the call to its `compress` method?

Also if you could wrap the code in a code block ([see here](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting)), that will make it easier to read.

**Comment by chnouman** [comment]
hy thanks for reply dear i have done this thanks for repy .

**Comment by mike183** [comment]
Can you provide the full contents of the file where you have done:

```php
compress("http://allhdwallpapers.com/sandbox/mediamanage/uploads//1119428508349446.jpg", "output.png");
print_r($singleImage);
?>
```

As the above snippet is incomplete.

**Comment by chnouman** [comment]
ok i'm done with it dear.
